# Generated by Django 3.2.12 on 2022-05-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.CharField(default='hello', max_length=80, unique=True),
            preserve_default=False,
        ),
    ]
