# Generated by Django 3.2.12 on 2022-05-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default=1, upload_to='images/profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='slug',
            field=models.CharField(default='your full name', max_length=80, unique=True),
        ),
    ]
