# Generated by Django 3.2.12 on 2022-05-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20220507_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
