# Generated by Django 3.2.12 on 2022-05-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_on_paid_leave',
            field=models.BooleanField(default=False),
        ),
    ]
