# Generated by Django 3.2.12 on 2022-05-09 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_auto_20220509_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='overtime_ended_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='overtime_stated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
