# Generated by Django 3.2.12 on 2022-05-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_shift_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='shift',
            field=models.CharField(choices=[('D', 'Day'), ('N', 'Night'), ('E', 'Evening')], default='D', help_text='Day Shift 5 day 40 hours', max_length=1),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(help_text='Day Shift 5 day 40 hours', max_length=30),
        ),
    ]
