# Generated by Django 3.2.12 on 2022-05-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_auto_20220513_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='operation',
            field=models.CharField(choices=[('BD', 'Bangladesh'), ('UA', 'Ukraine'), ('RS', 'Serbia')], default='BD', max_length=2),
        ),
    ]
