# Generated by Django 3.2.12 on 2022-05-14 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_schedule_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 14, 17, 34, 1, 525730), null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='overtime_ended_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 14, 17, 34, 1, 525741), null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='overtime_stated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 14, 17, 34, 1, 525736), null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 14, 17, 34, 1, 525718), null=True),
        ),
    ]
